#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# Clean cache of unused plugins
# call map(dein#check_clean(), "delete(v:val, 'rf')")
# call dein#recache_runtimepath()

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  # relativenumber = false
  guifont = "CaskaydiaCove Nerd Font:h18"
  # guifont = "DroidSansMono NF:h18"
  bootstrap_before = "config#before"
  bootstrap_after = "config#after"
  # autocomplete_method = "coc"
  default_indent = 2
  expand_tab = true

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"
  auto_completion_delay = 50
  auto_completion_complete_with_key_sequence = "nil"
  auto_completion_complete_with_key_sequence_delay = 0.1

[[layers]]
  name = 'shell'
  default_position = 'right'
  default_height = 50

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"
  git_plugin = "fugitive"
  git_diff_position = 'vsplit'

# [[layers]]
#   name = "lang#autohotkey"

# [[layers]]
#   name = "lang#javascript"
[[layers]]
  name = "lang#toml"

[[custom_plugins]]
  repo = "tpope/vim-commentary"

[[custom_plugins]]
  repo = "tpope/vim-surround"

[[custom_plugins]]
  repo = "tpope/vim-fugitive"

[[custom_plugins]]
  repo = "inkarkat/vim-ReplaceWithRegister"

[[custom_plugins]]
  repo = "christoomey/vim-sort-motion"

[[custom_plugins]]
  repo = "DanSM-5/vim-system-copy"

[[custom_plugins]]
  repo = "junegunn/fzf"

[[custom_plugins]]
  repo = "junegunn/fzf.vim"

[[custom_plugins]]
  repo = "mg979/vim-visual-multi"

[[custom_plugins]]
  repo = "dyng/ctrlsf.vim"

[[custom_plugins]]
  repo = "kreskij/Repeatable.vim"

[[custom_plugins]]
  repo = "bkad/CamelCaseMotion"

[[custom_plugins]]
  repo = "haya14busa/vim-asterisk"
