#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # relativenumber = false
    guifont = "DroidSansMono NF:h18" 
    bootstrap_before = "config#before"
    bootstrap_after = "config#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[custom_plugins]]
  repo = "tpope/vim-commentary"

[[custom_plugins]]
  repo = "tpope/vim-surround"

[[custom_plugins]]
  repo = "tpope/vim-fugitive"

[[custom_plugins]]
  repo = "inkarkat/vim-ReplaceWithRegister"

[[custom_plugins]]
  repo = "christoomey/vim-sort-motion"

[[custom_plugins]]
  repo = "DanSM-5/vim-system-copy"

[[custom_plugins]]
  repo = "junegunn/fzf"

[[custom_plugins]]
  repo = "mg979/vim-visual-multi"

[[custom_plugins]]
  repo = "dyng/ctrlsf.vim"
